--
-- PostgreSQL database dump
--

\restrict v2TmUWgu3POHbeOxHSQNKqmPCZUQRccaLSkOg7cscFuTFPqb3loK8MxEziZf8LV

-- Dumped from database version 14.24 (Debian 14.24-1.pgdg13+2)
-- Dumped by pg_dump version 14.24 (Debian 14.24-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: companies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.companies (
    id integer NOT NULL,
    address character varying(255),
    company_id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone,
    description text,
    email character varying(255),
    name character varying(255) NOT NULL,
    phone_number character varying(255),
    status character varying(255),
    updated_at timestamp(6) with time zone
);


--
-- Name: companies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: device_telemetry_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.device_telemetry_history (
    id uuid NOT NULL,
    altitude double precision,
    battery double precision,
    created_at timestamp(6) with time zone NOT NULL,
    device_sn character varying(255) NOT NULL,
    gps character varying(255),
    latitude double precision,
    longitude double precision,
    network character varying(255),
    recorded_at timestamp(6) with time zone NOT NULL,
    session_id uuid NOT NULL,
    speed double precision,
    status character varying(255)
);


--
-- Name: devices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.devices (
    id integer NOT NULL,
    brand_name character varying(255),
    created_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    description text,
    device_id uuid NOT NULL,
    device_name character varying(255) NOT NULL,
    device_sn character varying(255),
    device_type character varying(255),
    domain character varying(255),
    mission_id uuid,
    model character varying(255),
    status character varying(255),
    sub_type character varying(255),
    thing_version character varying(255),
    type character varying(255),
    updated_at timestamp(6) with time zone,
    company_id uuid,
    site_id uuid
);


--
-- Name: devices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: livestream_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.livestream_sessions (
    id uuid NOT NULL,
    device_sn character varying(255) NOT NULL,
    last_heartbeat_at timestamp(6) with time zone NOT NULL,
    mission_id uuid,
    playback_url text,
    quality character varying(255),
    session_status character varying(255),
    started_at timestamp(6) with time zone NOT NULL,
    stopped_at timestamp(6) with time zone,
    user_id uuid NOT NULL,
    video_id character varying(255)
);


--
-- Name: missions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.missions (
    id integer NOT NULL,
    company_id uuid,
    created_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    description text,
    device_type character varying(255),
    file character varying(255),
    location character varying(255),
    mission_id uuid NOT NULL,
    mission_name character varying(255) NOT NULL,
    mission_type character varying(255),
    site_id uuid,
    updated_at timestamp(6) with time zone
);


--
-- Name: missions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.missions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.missions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report_history (
    history_id uuid NOT NULL,
    company_id uuid,
    created_at timestamp(6) with time zone NOT NULL,
    detection_types text,
    device_sn character varying(255) NOT NULL,
    end_time timestamp(6) with time zone,
    main_detection_type character varying(255),
    mission_id uuid,
    playback_url text NOT NULL,
    session_id uuid,
    site_id uuid,
    start_time timestamp(6) with time zone,
    total_recognition integer,
    total_time character varying(255),
    user_id uuid,
    video_status character varying(255) NOT NULL,
    work_issue text
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(200),
    role_key character varying(64) NOT NULL
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sites (
    id integer NOT NULL,
    address character varying(255),
    company_id uuid,
    created_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    description text,
    email character varying(255),
    name character varying(255) NOT NULL,
    phone_number character varying(255),
    site_id uuid NOT NULL,
    timezone character varying(255),
    updated_at timestamp(6) with time zone
);


--
-- Name: sites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sub_devices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sub_devices (
    id bigint NOT NULL,
    deleted_at timestamp(6) with time zone,
    device_sn character varying(255),
    domain character varying(255),
    index character varying(255),
    model character varying(255),
    sn character varying(255),
    sub_device_id uuid,
    sub_type integer,
    thing_version character varying(255),
    type integer
);


--
-- Name: sub_devices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sub_devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sub_devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_devices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_devices (
    user_id uuid NOT NULL,
    device_id uuid NOT NULL
);


--
-- Name: user_missions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_missions (
    user_id uuid NOT NULL,
    mission_id uuid NOT NULL
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    id bigint NOT NULL,
    assigned_at timestamp(6) with time zone NOT NULL,
    assigned_by uuid,
    role_id integer NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: user_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_sites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_sites (
    user_id uuid NOT NULL,
    site_id uuid NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    company_id uuid,
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone,
    description text,
    email character varying(255) NOT NULL,
    full_name character varying(255),
    is_active boolean NOT NULL,
    last_login_at timestamp(6) with time zone,
    password_hash character varying(255) NOT NULL,
    phone character varying(50),
    updated_at timestamp(6) with time zone NOT NULL,
    user_id uuid NOT NULL,
    username character varying(255) NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- Name: device_telemetry_history device_telemetry_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_telemetry_history
    ADD CONSTRAINT device_telemetry_history_pkey PRIMARY KEY (id);


--
-- Name: devices devices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (id);


--
-- Name: livestream_sessions livestream_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.livestream_sessions
    ADD CONSTRAINT livestream_sessions_pkey PRIMARY KEY (id);


--
-- Name: missions missions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.missions
    ADD CONSTRAINT missions_pkey PRIMARY KEY (id);


--
-- Name: report_history report_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_history
    ADD CONSTRAINT report_history_pkey PRIMARY KEY (history_id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: sites sites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sites
    ADD CONSTRAINT sites_pkey PRIMARY KEY (id);


--
-- Name: sub_devices sub_devices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sub_devices
    ADD CONSTRAINT sub_devices_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users uk6efs5vmce86ymf5q7lmvn2uuf; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6efs5vmce86ymf5q7lmvn2uuf UNIQUE (user_id);


--
-- Name: missions uk9pa8wwi0owx9759in3yinnfd5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.missions
    ADD CONSTRAINT uk9pa8wwi0owx9759in3yinnfd5 UNIQUE (mission_id);


--
-- Name: report_history uk_report_history_device_playback; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_history
    ADD CONSTRAINT uk_report_history_device_playback UNIQUE (device_sn, playback_url);


--
-- Name: user_roles uka9dydk3dj4qb8cvmjijqnrg5t; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT uka9dydk3dj4qb8cvmjijqnrg5t UNIQUE (user_id, role_id);


--
-- Name: companies ukd4qql6qgvrphasg6gkelogfur; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT ukd4qql6qgvrphasg6gkelogfur UNIQUE (company_id);


--
-- Name: devices ukdmhx1c1qgokkb3lwfw7opwyjt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT ukdmhx1c1qgokkb3lwfw7opwyjt UNIQUE (device_sn);


--
-- Name: sites ukg9a13sqlcciu7kuf0upwrvo4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sites
    ADD CONSTRAINT ukg9a13sqlcciu7kuf0upwrvo4 UNIQUE (site_id);


--
-- Name: roles ukhv4h8ntv1nqbxgh7c4e6tevy4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukhv4h8ntv1nqbxgh7c4e6tevy4 UNIQUE (role_key);


--
-- Name: devices ukkl1viut5wsyxgnd1t3wqf9hbu; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT ukkl1viut5wsyxgnd1t3wqf9hbu UNIQUE (device_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: user_devices user_devices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_devices
    ADD CONSTRAINT user_devices_pkey PRIMARY KEY (user_id, device_id);


--
-- Name: user_missions user_missions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_missions
    ADD CONSTRAINT user_missions_pkey PRIMARY KEY (user_id, mission_id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);


--
-- Name: user_sites user_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sites
    ADD CONSTRAINT user_sites_pkey PRIMARY KEY (user_id, site_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_device_telemetry_device_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_device_telemetry_device_time ON public.device_telemetry_history USING btree (device_sn, recorded_at);


--
-- Name: idx_device_telemetry_session_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_device_telemetry_session_time ON public.device_telemetry_history USING btree (session_id, recorded_at);


--
-- Name: devices fkgftgwq73nq3aymdfb88hagr1f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT fkgftgwq73nq3aymdfb88hagr1f FOREIGN KEY (company_id) REFERENCES public.companies(company_id);


--
-- Name: devices fkit1auw1j4l9k1l3mn656ee5li; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT fkit1auw1j4l9k1l3mn656ee5li FOREIGN KEY (site_id) REFERENCES public.sites(site_id);


--
-- PostgreSQL database dump complete
--

\unrestrict v2TmUWgu3POHbeOxHSQNKqmPCZUQRccaLSkOg7cscFuTFPqb3loK8MxEziZf8LV
