server:
  port: 6789

spring:
  application:
    name: dhive

  datasource:
    url: jdbc:postgresql://localhost:5432/dhive-main
    username: postgres
    password: Ashwin@11
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.security: INFO
    com.dji.sample: DEBUG


app:
  jwt:
    secret: "my-super-secret-key-my-super-secret-key-123456"
    # access-token-expiration-ms: 3600000
    access-token-expiration-ms: 86400000
    refresh-token-expiration-ms: 259200000
  upload:
    mission-dir: uploads/missions

cors:
  allowed-origin-patterns: "http://localhost:5173,http://127.0.0.1:5173"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

aws:
  region: ap-northeast-2
  s3:
    mission-bucket: robopilot-mission
    stream-bucket: robopilot-stream-data