server:
  port: 6789

spring:
  application:
    name: dhive

  datasource:
    url: jdbc:postgresql://localhost:5432/dhive-main
    username: postgres
    password: Ashwin@11
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
    
  redis:
    device-alive-second: 84600

logging:
  level:
    org.springframework.security: INFO
    # com.dji.sample: DEBUG
    com.dji.sample: INFO
    org.hibernate.SQL: OFF


app:
  jwt:
    secret: "my-super-secret-key-my-super-secret-key-123456"
    # access-token-expiration-ms: 3600000
    access-token-expiration-ms: 86400000
    refresh-token-expiration-ms: 259200000
  upload:
    mission-dir: uploads/missions

cors:
  allowed-origin-patterns: "http://localhost:5173,http://127.0.0.1:5173"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

aws:
  region: ap-northeast-2
  s3:
    mission-bucket: robopilot-mission
    stream-bucket: robopilot-stream-data


mqtt:
  enabled: true
  host: localhost
  port: 1883
  client-id: dhive-local-backend-go2-test
  username: cloud-server
  password: QAZ1357okm24
  inbound-topic: sys/product/+/status,thing/product/+/osd,thing/product/+/state,thing/product/+/services_reply,robot/+/health,robot/+/response,robot/+/job/state,robot/+/state,robot/+/telemetry

cloud-sdk:
  mqtt:
    inbound-topic: sys/product/+/status,thing/product/+/osd,thing/product/+/state,thing/product/+/services_reply,robot/+/health,robot/+/response,robot/+/job/state,robot/+/state,robot/+/telemetry


ai-service:
  base-url: http://localhost:7879
  stream-endpoint: /api/stream
  timeout: 10000
  # rtmp-url: rtmp://10.17.14.101:1935
  rtmp-url: rtmp://43.202.9.216:1935

slack:
  enabled: ${SLACK_ENABLED:false}
  bot-token: ${SLACK_BOT_TOKEN:}
