package com.dji.sample.config;

import com.dji.sdk.cloudapi.device.UpdateTopo;
import com.dji.sdk.common.Common;
import com.dji.sdk.mqtt.ChannelName;
import com.dji.sdk.mqtt.IMqttMessageGateway;
import com.dji.sdk.mqtt.MqttGatewayPublish;
import com.dji.sdk.mqtt.services.ServicesPublish;
import com.dji.sdk.mqtt.services.ServicesReplyHandler;
import com.dji.sdk.mqtt.status.TopicStatusRequest;
import com.dji.sdk.mqtt.status.TopicStatusResponse;
import com.fasterxml.jackson.core.type.TypeReference;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.integration.annotation.IntegrationComponentScan;
import org.springframework.integration.annotation.ServiceActivator;
import org.springframework.integration.channel.DirectChannel;
import org.springframework.integration.dsl.IntegrationFlow;
import org.springframework.integration.mqtt.core.MqttPahoClientFactory;
import org.springframework.integration.mqtt.outbound.MqttPahoMessageHandler;
import org.springframework.integration.mqtt.support.DefaultPahoMessageConverter;
import org.springframework.integration.mqtt.support.MqttHeaders;
import org.springframework.messaging.Message;
import org.springframework.messaging.MessageChannel;
import org.springframework.messaging.MessageHandler;
import org.springframework.util.CollectionUtils;
import org.springframework.util.ReflectionUtils;

import java.lang.reflect.Field;
import java.util.UUID;

@Configuration
@IntegrationComponentScan(basePackageClasses = IMqttMessageGateway.class)
public class DjiMqttSdkPublishConfig {

    @Bean
    public ServicesReplyHandler servicesReplyHandler() {
        return new ServicesReplyHandler();
    }

    @Bean
    public IntegrationFlow djiServicesReplyFlow(
            ServicesReplyHandler servicesReplyHandler
    ) {
        return IntegrationFlow
                .from(ChannelName.INBOUND_SERVICES_REPLY)
                .handle(servicesReplyHandler, "servicesReply")
                .get();
    }

    @Bean
    public MqttGatewayPublish mqttGatewayPublish(
            IMqttMessageGateway messageGateway,
            MqttPahoClientFactory mqttClientFactory
    ) {
        MqttGatewayPublish bean = new MqttGatewayPublish();

        setField(bean, "messageGateway", messageGateway);
        setField(bean, "mqttClientFactory", mqttClientFactory);

        return bean;
    }

    @Bean
    public ServicesPublish servicesPublish(
            MqttGatewayPublish mqttGatewayPublish
    ) {
        ServicesPublish bean = new ServicesPublish();

        setField(bean, "gatewayPublish", mqttGatewayPublish);

        return bean;
    }

    /*
     * Local replacement for cloud-sdk StatusRouter.
     *
     * cloud-sdk 1.0.3 uses the removed IntegrationFlows class and is not
     * directly compatible with the current Spring Integration version.
     */
    @Bean
    public IntegrationFlow djiStatusRouterFlow() {
        return IntegrationFlow
                .from(ChannelName.INBOUND_STATUS)
                .transform(Message.class, this::parseStatusMessage)
                .<TopicStatusRequest<UpdateTopo>, Boolean>route(
                        this::isStatusOffline,
                        router -> router
                                .channelMapping(
                                        Boolean.TRUE,
                                        ChannelName.INBOUND_STATUS_OFFLINE
                                )
                                .channelMapping(
                                        Boolean.FALSE,
                                        ChannelName.INBOUND_STATUS_ONLINE
                                )
                )
                .get();
    }

    /*
     * Publish the status reply generated by DjiDeviceStatusHandler.
     */
    @Bean
    public IntegrationFlow djiStatusReplyFlow(
            MqttGatewayPublish mqttGatewayPublish
    ) {
        return IntegrationFlow
                .from(ChannelName.OUTBOUND_STATUS)
                .handle(
                        TopicStatusResponse.class,
                        (response, headers) -> {
                            if (response != null) {
                                mqttGatewayPublish.publishReply(
                                        response,
                                        headers
                                );
                            }

                            return null;
                        }
                )
                .get();
    }

    @Bean
    @ServiceActivator(inputChannel = ChannelName.OUTBOUND)
    public MessageHandler djiMqttOutbound(
            MqttPahoClientFactory mqttClientFactory
    ) {
        MqttPahoMessageHandler handler =
                new MqttPahoMessageHandler(
                        UUID.randomUUID().toString(),
                        mqttClientFactory
                );

        DefaultPahoMessageConverter converter =
                new DefaultPahoMessageConverter();

        converter.setPayloadAsBytes(true);

        handler.setAsync(true);
        handler.setDefaultQos(0);
        handler.setConverter(converter);

        return handler;
    }

    @Bean(name = ChannelName.INBOUND_STATUS)
    public MessageChannel djiInboundStatusChannel() {
        return new DirectChannel();
    }

    @Bean(name = ChannelName.INBOUND_STATUS_ONLINE)
    public MessageChannel djiInboundStatusOnlineChannel() {
        return new DirectChannel();
    }

    @Bean(name = ChannelName.INBOUND_STATUS_OFFLINE)
    public MessageChannel djiInboundStatusOfflineChannel() {
        return new DirectChannel();
    }

    @Bean(name = ChannelName.OUTBOUND_STATUS)
    public MessageChannel djiOutboundStatusChannel() {
        return new DirectChannel();
    }

    private TopicStatusRequest<UpdateTopo> parseStatusMessage(
            Message<?> message
    ) {
        try {
            Object payload = message.getPayload();

            if (!(payload instanceof byte[] payloadBytes)) {
                throw new IllegalArgumentException(
                        "DJI status payload must be byte[] but was: "
                                + payload.getClass().getName()
                );
            }

            TopicStatusRequest<UpdateTopo> request =
                    Common.getObjectMapper().readValue(
                            payloadBytes,
                            new TypeReference<
                                    TopicStatusRequest<UpdateTopo>
                            >() {
                            }
                    );

            Object receivedTopic = message
                    .getHeaders()
                    .get(MqttHeaders.RECEIVED_TOPIC);

            String topic = String.valueOf(receivedTopic);

            String topicPrefix = "sys/product/";
            String topicSuffix = "/status";

            int serialStart = topic.indexOf(topicPrefix);
            int serialEnd = topic.indexOf(topicSuffix);

            if (serialStart < 0 || serialEnd < 0) {
                throw new IllegalArgumentException(
                        "Invalid DJI status topic: " + topic
                );
            }

            serialStart += topicPrefix.length();

            if (serialEnd <= serialStart) {
                throw new IllegalArgumentException(
                        "Unable to extract DJI gateway serial from topic: "
                                + topic
                );
            }

            request.setFrom(
                    topic.substring(serialStart, serialEnd)
            );

            return request;

        } catch (Exception exception) {
            throw new IllegalStateException(
                    "Failed to parse DJI status MQTT message",
                    exception
            );
        }
    }

    private boolean isStatusOffline(
            TopicStatusRequest<UpdateTopo> request
    ) {
        if (request == null || request.getData() == null) {
            return true;
        }

        return CollectionUtils.isEmpty(
                request.getData().getSubDevices()
        );
    }

    private static void setField(
            Object target,
            String fieldName,
            Object value
    ) {
        Field field = ReflectionUtils.findField(
                target.getClass(),
                fieldName
        );

        if (field == null) {
            throw new IllegalStateException(
                    "Field not found: " + fieldName
            );
        }

        ReflectionUtils.makeAccessible(field);
        ReflectionUtils.setField(field, target, value);
    }
}