services:
  robopilot-backend:
    container_name: robopilot-backend
    image: robopilot-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "6790:6789"
    env_file:
      - .env.internal
    environment:
      TZ: Asia/Seoul
      AWS_REGION: ap-northeast-2
    networks:
      - dhive-network

networks:
  dhive-network:
    external: true
    name: cloud_service_dhive-network